### ISSUE TITLE
Authors in released opam file?

### ISSUE THREAD

**Issue by brabalan** [querycert/jsast#1]
Hello,

I'm very glad to see (tiny) parts of JSCert being used. I would be happier if the original authors were also mentioned in the released opam file (https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-jsast/coq-jsast.1.0.9/opam).

Thank a lot,

Alan Schmitt

**Comment by mandel** [comment]
Hi Alan,

Of course, you are completely right! It should be fixed by https://github.com/coq/opam-coq-archive/pull/1340.

**Comment by jeromesimeon** [comment]
Yes it was really my bad. 😦 I think when we did it we hoped it would be temporary. Thanks for catching this!

**Comment by brabalan** [comment]
Thanks a lot Louis and Jérôme!
